### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by dalance** [RuSys/Verugent#1]
Rust library should be published to https://crates.io.
If published, it can be used more easily like below:

```
[dependencies]
Verugent = "0.1.0"
```

**Comment by merbaum7** [comment]
Thank you for your nice suggestion.
I will publish this library to crate.io soon.

**Comment by dalance** [comment]
Thanks!
The links to crates.io/docs.rs like below may be useful.

```
[![Crates.io](https://img.shields.io/crates/v/verugent.svg)](https://crates.io/crates/verugent)
[![Docs.rs](https://docs.rs/verugent/badge.svg)](https://docs.rs/verugent)
```

**Comment by merbaum7** [comment]
I added your suggested links.
Thanks again!

**Comment by dalance** [comment]
Thanks. I'll try to use.
